Educacesso.MVC/Controllers/FazerCursoController.cs
using AutoMapper;
using Educacesso.Domain.Entities;
using Educacesso.MVC.ViewModels;
using EducacessoV2.Application.Interfaces;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Educacesso.MVC.Controllers
{
    public class FazerCursoController : Controller
    {

        private readonly ICursoAppService _cursoApp;
        private readonly ILicaoAppService _licaoApp;

        public FazerCursoController(ICursoAppService cursoApp, ILicaoAppService licaoApp)
        {
            _cursoApp = cursoApp;
            _licaoApp = licaoApp;
        }

        //
        // GET: /FazerCurso/
        public ActionResult Index(int id = 1)
        {
            
            ViewBag.TituloLicao = new SelectList(_licaoApp.LicoesDoCursoSelecionado(id), "LicaoID", "Titulo_Licao");
            var licaoViewModel = Mapper.Map<IEnumerable<Licao>, IEnumerable<LicaoViewModel>>(_licaoApp.GetAll());
			var licaoView = new LicaoViewModel();
            return View(licaoView);
        }

        [HttpPost, ActionName("Index")]
        [ValidateAntiForgeryToken]
        public ActionResult Licao(int TituloLicao) // TituloLicao = ID da lição
        {
			
			
			 var licaoSelecionada = Mapper.Map<Licao, LicaoViewModel>(_licaoApp.GetLicaoById(TituloLicao));
            ViewBag.TituloLicao = new SelectList(_licaoApp.LicoesDoCursoSelecionado(licaoSelecionada.CursoID), "LicaoID", "Titulo_Licao");
			


			return View(licaoSelecionada);
        }

     
	}
}

Educacesso.MVC/Controllers/PesquisarController.cs
using AutoMapper;
using Educacesso.Domain.Entities;
using Educacesso.MVC.ViewModels;
using EducacessoV2.Application.Interfaces;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Educacesso.MVC.Controllers
{
    public class PesquisarController : Controller
    {
        private readonly ICursoAppService _cursoApp;
        public UserManager<UserIdentity> UserManager { get; private set; }

        public PesquisarController(ICursoAppService cursoApp)
        {
            _cursoApp = cursoApp;
        }

        public PesquisarController(UserManager<UserIdentity> userManager)
        {
            UserManager = userManager;
        }



        //
        // GET: /Pesquisar/
        public ActionResult Index()
        {
           var cursoViewModel = Mapper.Map<IEnumerable<Curso>, IEnumerable<Curso>>(null);
           
            return View(cursoViewModel);
        }

        [HttpPost]
        public ActionResult Index(string searchTerm)
        {


            IEnumerable<Curso> lcursos;


            if (string.IsNullOrEmpty(searchTerm)) 
                lcursos = _cursoApp.GetAll(); 
            else          
                lcursos = _cursoApp.BuscarCursosAutocomplete(searchTerm);
            
            //
            return View(lcursos);
            
        }

       
        public JsonResult GetCursos(string term)
        {
            

            List<string> cursos = _cursoApp.BuscarCursosAutocomplete(term).Distinct().Select(y => y.Nome_Curso).ToList();

            return Json(cursos, JsonRequestBehavior.AllowGet);
        }

    }
}

Educacesso.MVC/Views/Pesquisar/Index.cshtml
@model IEnumerable<Educacesso.Domain.Entities.Curso>




<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
@using (@Html.BeginForm())
{
    <div class="panel panel-primary">
        <div class="panel-heading">
            <h3 class="panel-title"><strong>Pesquise cursos aqui!</strong> </h3>
        </div>
        <div class="panel-body">
            <form class="navbar-form navbar-left searchColor" role="search">
                <div class="form-group">
					<input type="text" id="txtSearch" name="searchTerm" class="form-control searchColor borderC" placeholder="Digite aqui...">
					<button type="submit" class="btn btn-default btnPesquisar">Buscar</button>
                </div>
               
            </form>
        </div>
    </div>




}

<br />
<br />
<br />
<br />

    <table class="table table-striped table-hover">
        <thead>
            <tr class="danger">

                <th>@Html.DisplayName("Nome") </th>
                <th>@Html.DisplayName("Resumo") </th>
                <th> </th>

            </tr>
        </thead>
     


        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Nome_Curso)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Resumo_Curso)
                </td>
                <td>

                    @Html.ActionLink("Ver Curso", "Index", "FazerCurso", new { id = item.CursoID }, null)

                </td>
            </tr>
        }

    </table>



@section Scripts{

<script src="~/Scripts/AutoComplete/jquery-ui.js"></script>
<link href="~/Content/jquery-ui.css" rel="stylesheet" />


<script type="text/javascript">
        $(function () {
            $('#txtSearch').autocomplete({
                source: '@Url.Action("GetCursos")',
                minLength: 2
            });
        });
</script>
}