Educacesso.MVC/Controllers/ListaCursosController.cs
using AutoMapper;
using Educacesso.Domain.Entities;
using Educacesso.MVC.ViewModels;
using EducacessoV2.Application.Interfaces;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Educacesso.MVC.Controllers
{
    public class ListaCursosController : Controller
    {

		private readonly ICursoAppService _cursoApp;

		public ListaCursosController(ICursoAppService cursoApp)
		{
			_cursoApp = cursoApp;
		}

        //
        // GET: /ListaCursos/
        public ActionResult Index(string Id)
        {
			var cursoViewModel = Mapper.Map<IEnumerable<Curso>, IEnumerable<CursoViewModel>>(_cursoApp.CursosDoUsuarioLogado(Id));
            return View(cursoViewModel);
        }
	}
}

Educacesso.MVC/Controllers/PerfilController.cs
using AutoMapper;
using Educacesso.Domain.Entities;
using Educacesso.MVC.ViewModels;
using EducacessoV2.Application.Interfaces;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Educacesso.MVC.Controllers
{
    public class PerfilController : Controller
    {

        private readonly IAmigoAppService _amigoAppService;
        private readonly IAmigoUsuarioAppService _amigoUsuarioAppService;
        private readonly IUserAppService _userAppService;

        public PerfilController(IAmigoAppService amigoAppService, IAmigoUsuarioAppService amigoUsuarioAppService, IUserAppService userAppService)
        {
            _amigoAppService = amigoAppService;
            _amigoUsuarioAppService = amigoUsuarioAppService;
            _userAppService = userAppService;
        }


        public PerfilController(UserManager<UserIdentity> userManager)
        {
            UserManager = userManager;
        }

        public UserManager<UserIdentity> UserManager { get; private set; }






        #region Actions
        public ActionResult MeuPerfil()
        {
            var usuarioLogado = _userAppService.GetByID(User.Identity.GetUserId());
            return View(usuarioLogado);
        }


        public ActionResult Index()
        {
            return RedirectToAction("Manage", "Account");
        }
       
        public ActionResult Seguindo()
        {
          
            //LISTA DE AMIGOS
            List<AmigoUsuario> lamigoUsuario = _amigoUsuarioAppService.ListaDeIdDeAmigos(User.Identity.GetUserId()); //Buscando os amigos do usuario
            List<Amigo> lamigo = _amigoAppService.ListaAmigosDoUsuario(lamigoUsuario); // uma lista de Amigos Do usuario que está logado

            List<UserIdentity> listaSeguindo = new List<UserIdentity>();
            foreach (var item in lamigo)
            {
             var users =  _userAppService.GetByID(item.UserIdentityId);
                listaSeguindo.Add(users);
            }
           
            return View(listaSeguindo);
        }


        public ActionResult BuscarUsuarios()
        {
            var usuario = _userAppService.GetAll(); // PAGINA ADD AMIGO, Exibe uma lista de usuarios para seguir
            List<UserIdentity> list = usuario.ToList();

            List<AmigoUsuario> lamigoUsuario = _amigoUsuarioAppService.ListaDeIdDeAmigos(User.Identity.GetUserId()); //Buscando os amigos do usuario
            List<Amigo> lamigo = _amigoAppService.ListaAmigosDoUsuario(lamigoUsuario);

            #region remover da lista amigos que o usuario já segue
            foreach (var usuarios in usuario)
            {
                foreach (var meusAmigos in lamigo)
                {
                    if (usuarios.Id == meusAmigos.UserIdentityId || usuarios.Id == User.Identity.GetUserId())
                    {
                        list.Remove(usuarios);
                    }
                }

            }
            #endregion

            return View(list);
        }

        
        public ActionResult Adicionar(string Id)
        {         
            var umAmigo = _userAppService.GetByID(Id);
            int idAmigoAdicionado = _amigoAppService.addAmigo(umAmigo);

			umAmigo.QtdSeguidores += 1;
			_userAppService.Update(umAmigo);
            _amigoUsuarioAppService.addAmigo(idAmigoAdicionado, User.Identity.GetUserId());
            return RedirectToAction("Index");
        }

        #endregion


    }
}

Educacesso.MVC/Views/Perfil/BuscarUsuarios.cshtml
@model IEnumerable<Educacesso.Domain.Entities.UserIdentity>

@{
    ViewBag.Title = "Amigos";
}
<div class="fundoBuscarusuario">
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <input type="text" placeholder="buscar usuarios" value=" " class="buscarSeguidores"/>
    <input type="button" value="Buscar" class="botaoBuscarSeguidores"/>
    <h4>Siga Usuarios</h4>
    <div class="list-group">
        <a href="Index" class="list-group-item ">
            Perfil
        </a>
        <a href="" class="list-group-item">
            Mensagens <span class="badge">14</span>
        </a>
        <a href="~/Perfil/Seguindo" class="list-group-item">
            Seguinte
        </a>
        <a href="~/Perfil/BuscarUsuarios" class="list-group-item active">
            Buscar Usuarios
        </a>
    </div>



    @foreach (var item in Model)
    {
        <div class="listaSeguir">
          
            <span class="seguidoresNome">  @Html.DisplayFor(modelItem => item.UserName) </span>

            <span class="qtdSeguidores">Seguidores</span><span class="badge qtdSeguidores novaCor">@Html.DisplayFor(modelItem => item.QtdSeguidores) </span>

            @Html.ActionLink("Seguir", "Adicionar", new { id = item.Id }, new{@class="adicionarSeguir"})

        </div>
    }

</div>

Educacesso.MVC/Views/Perfil/MeuPerfil.cshtml
@model Educacesso.Domain.Entities.UserIdentity

@{
    ViewBag.Title = "MeuPerfil";
}

<br />
<br />
<br />
<br />
<h2>Meu Perfil</h2>

<div>
    
	<hr />
    <div class="right">
        
            @Html.DisplayNameFor(model => model.UserName)
       

       
            @Html.DisplayFor(model => model.UserName)
       

    </div>
</div>

<div class="list-group">
    <a href="Index" class="list-group-item active">
        Perfil
    </a>
    <a href="#" class="list-group-item">
        Mensagens <span class="badge">14</span>
    </a>
    <a href="~/Perfil/Seguindo" class="list-group-item">
       Seguindo
    </a>
    <a href="~/Perfil/BuscarUsuario" class="list-group-item">
        Buscar Usuarios
    </a>
</div>

Educacesso.MVC/Views/Perfil/Seguindo.cshtml
@model List<Educacesso.Domain.Entities.UserIdentity>

    ViewBag.Title = "Index";
}

<br />
<br />
<br />
<br />
<br />
<h2>Seguindo</h2>
<div class="list-group">
    <a href="Index" class="list-group-item ">
        Perfil
    </a>
    <a href="" class="list-group-item">
        Mensagens <span class="badge">14</span>
    </a>
    <a href="~/Perfil/Seguindo" class="list-group-item active">
        Seguindo
    </a>
    <a href="~/Perfil/BuscarUsuarios" class="list-group-item">
        Buscar Usuarios
    </a>
</div>


@foreach (var item in Model)
{

    <div class="listaSeguir">
       
        <span class="seguidoresNome">
            @Html.DisplayFor(modelItem => item.UserName) </span>
            <span class="qtdSeguidores">Seguidores</span><span class="badge qtdSeguidores novaCor">@Html.DisplayFor(model => item.QtdSeguidores) </span>

            @Html.ActionLink("Ver cursos", "Index", "ListaCursos", new { id = item.Id }, new { @class = "adicionarSeguir verCanal" })

</div>
}